/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package klinik.main;

import klinik.entity.pasien;
import klinik.entity.jadwal;
import klinik.exec.ExecutePsn;
import klinik.exec.ExecuteTransaksi;
import klinik.entity.obat;
import klinik.exec.ExecuteJadwal;
import klinik.exec.ExecuteObat;
import klinik.entity.convertclasstoobject;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;
import klinik.entity.transaksi;
//import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class MainFormStore extends javax.swing.JFrame {


    /**
     * Creates new form MainFormStore
     */
    //DefaultTableModel model;
    
    public MainFormStore() {
        initComponents();
        setDataPasien();
        setDataObat();
        setDataJadwal();
        setDataTransaksi();
        //setDataPembelianObat();
        //setDataDistributor();
    }

    /**
     * This method is calledfrom within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void setDataPasien(){
        convertclasstoobject ccto = new convertclasstoobject();
        String[][] datapasien = ccto.getAllpasien();
        tblPasien.setModel(new javax.swing.table.DefaultTableModel(
            datapasien,
            new String [] {
                "Id Pasien", "Nama", "Alamat", "Gender","Nomor Telefon","Pekerjaan","Tanggal Cekup"
            }
        ));
        jScrollPane2.setViewportView(tblPasien);
        tblPembelianpsn.setModel(new javax.swing.table.DefaultTableModel(
            datapasien,
            new String [] {
                "Id Pasien", "Nama", "Alamat", "Gender","Nomor Telefon","Pekerjaan","Tanggal Cekup"
            }
        ));
        jScrollPane6.setViewportView(tblPembelianpsn);
    }   
    
    private void setDataObat(){
        convertclasstoobject ccto = new convertclasstoobject();
        String[][] dataobat = ccto.getAllObat();
        tblObat.setModel(new javax.swing.table.DefaultTableModel(
            dataobat,
            new String [] {
                "Id Obat", "Nama Obat", "Jenis Obat", "Harga"
            }
        ));
        jScrollPane3.setViewportView(tblObat);
        
        tblPembelianobat.setModel(new javax.swing.table.DefaultTableModel(
            dataobat,
            new String [] {
                "Id Obat", "Nama Obat", "Jenis Obat", "Harga"
            }
        ));
        jScrollPane7.setViewportView(tblPembelianobat);
    } 
     
    private void setDataJadwal(){
        convertclasstoobject ccto = new convertclasstoobject();
        String[][] datajadwal = ccto.getAlljadwal();
        tblJadwal.setModel(new javax.swing.table.DefaultTableModel(
            datajadwal,
            new String [] {
                "Id Jadwal", "Id Dokter", "Nama Dokter", "Tanggal Praktek", "Spesialis"
            }
        ));
        jScrollPane4.setViewportView(tblJadwal);
    } 
        
    private void setDataTransaksi(){
        convertclasstoobject ccto = new convertclasstoobject();
        String[][] datatransaksi = ccto.getAllTransaksi();
        tblTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            datatransaksi,
            new String [] {
                "Id Transaksi", "Id Dokter", "Id Pasien", "Nama Pasien","Id Obat","Quantity","Harga Obat","Total Harga"
            }
        ));
        jScrollPane9.setViewportView(tblTransaksi);
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnPasien = new javax.swing.JButton();
        btnObat = new javax.swing.JButton();
        btnJadwal = new javax.swing.JButton();
        btnPembelian = new javax.swing.JButton();
        btnTransaksi = new javax.swing.JButton();
        pnlUtama = new javax.swing.JPanel();
        pnlPasien = new javax.swing.JPanel();
        pnlInputBuku = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtIdpasien = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        txtAlam = new javax.swing.JTextField();
        cbbGender = new javax.swing.JComboBox<>();
        txtNotelp = new javax.swing.JTextField();
        txtPekerjaan = new javax.swing.JTextField();
        btnSimpanPSN = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        DateChoose = new com.toedter.calendar.JDateChooser();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPasien = new javax.swing.JTable();
        pnlTblBuku = new javax.swing.JPanel();
        pnlObat = new javax.swing.JPanel();
        pnlInputBuku1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtIdobat = new javax.swing.JTextField();
        txtNamaobat = new javax.swing.JTextField();
        cbbobat = new javax.swing.JComboBox<>();
        txtHarga = new javax.swing.JTextField();
        btnSimpanObat = new javax.swing.JButton();
        btnHapus1 = new javax.swing.JButton();
        btnUpdate1 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblObat = new javax.swing.JTable();
        pnlJadwal = new javax.swing.JPanel();
        pnlInputBuku2 = new javax.swing.JPanel();
        btnHapusjdw = new javax.swing.JButton();
        btnUpdatejdw = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        btnSimpanjdw = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtIdjadwal = new javax.swing.JTextField();
        txtIddokter = new javax.swing.JTextField();
        txtNamadokter = new javax.swing.JTextField();
        txtSpesialis = new javax.swing.JTextField();
        DateChoose1 = new com.toedter.calendar.JDateChooser();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblJadwal = new javax.swing.JTable();
        pnlPembelian = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblPembelianpsn = new javax.swing.JTable();
        jScrollPane7 = new javax.swing.JScrollPane();
        tblPembelianobat = new javax.swing.JTable();
        jId_dokter = new javax.swing.JTextField();
        jId_pasien = new javax.swing.JTextField();
        jNama_pasien = new javax.swing.JTextField();
        jId_obat = new javax.swing.JTextField();
        jHarga_obat = new javax.swing.JTextField();
        jTotalharga = new javax.swing.JTextField();
        lblHarga = new javax.swing.JLabel();
        jQty = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        btnpesan = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        pnlTransaksi = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        tblTransaksi = new javax.swing.JTable();
        txtcetaktotal = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        txtcetakidtrans = new javax.swing.JTextField();
        txtcetakidpasien = new javax.swing.JTextField();
        txtcetaknamapasien = new javax.swing.JTextField();
        txtcetakqty = new javax.swing.JTextField();
        txtcetakharga = new javax.swing.JTextField();
        btnCetak = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        area = new javax.swing.JTextArea();
        btnCetakstruk = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        btnPasien.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPasien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/klinik/icon/seo-report.png"))); // NOI18N
        btnPasien.setText("Registrasi Pasien");
        btnPasien.setFocusable(false);
        btnPasien.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPasien.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPasienActionPerformed(evt);
            }
        });
        jToolBar1.add(btnPasien);

        btnObat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnObat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/klinik/icon/medicine.png"))); // NOI18N
        btnObat.setText("Daftar Obat");
        btnObat.setFocusable(false);
        btnObat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnObat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnObat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObatActionPerformed(evt);
            }
        });
        jToolBar1.add(btnObat);

        btnJadwal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnJadwal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/klinik/icon/calendar (1).png"))); // NOI18N
        btnJadwal.setText("Jadwal Checkup");
        btnJadwal.setFocusable(false);
        btnJadwal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnJadwal.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnJadwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJadwalActionPerformed(evt);
            }
        });
        jToolBar1.add(btnJadwal);

        btnPembelian.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPembelian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/klinik/icon/transaction.png"))); // NOI18N
        btnPembelian.setText("Pembelian");
        btnPembelian.setFocusable(false);
        btnPembelian.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPembelian.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPembelianActionPerformed(evt);
            }
        });
        jToolBar1.add(btnPembelian);

        btnTransaksi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTransaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/klinik/icon/wallet.png"))); // NOI18N
        btnTransaksi.setText("Data Transaksi");
        btnTransaksi.setFocusable(false);
        btnTransaksi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTransaksi.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransaksiActionPerformed(evt);
            }
        });
        jToolBar1.add(btnTransaksi);

        pnlUtama.setLayout(new java.awt.CardLayout());

        pnlInputBuku.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("Registrasi Pasien");
        pnlInputBuku.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel3.setText("Id Pasien");
        pnlInputBuku.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel4.setText("Alamat");
        pnlInputBuku.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel5.setText("Gender");
        pnlInputBuku.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, -1, -1));

        jLabel6.setText("Tanggal Cekup");
        pnlInputBuku.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        txtIdpasien.setEnabled(false);
        pnlInputBuku.add(txtIdpasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 180, -1));
        pnlInputBuku.add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 180, -1));
        pnlInputBuku.add(txtAlam, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 180, -1));

        cbbGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pria", "Wanita" }));
        pnlInputBuku.add(cbbGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, 180, -1));

        txtNotelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNotelpActionPerformed(evt);
            }
        });
        pnlInputBuku.add(txtNotelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, 180, -1));
        pnlInputBuku.add(txtPekerjaan, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, 180, -1));

        btnSimpanPSN.setText("Simpan");
        btnSimpanPSN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanPSNActionPerformed(evt);
            }
        });
        pnlInputBuku.add(btnSimpanPSN, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 60, -1, -1));

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        pnlInputBuku.add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 140, 70, -1));

        btnUpdate.setText("Ubah");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        pnlInputBuku.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 100, 70, -1));

        jLabel17.setText("Nama");
        pnlInputBuku.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel18.setText("Telefon");
        pnlInputBuku.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, -1, -1));
        pnlInputBuku.add(DateChoose, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, -1, -1));

        jLabel12.setText("Pekerjaan");
        pnlInputBuku.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, -1, -1));

        tblPasien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPasien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPasienMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblPasien);

        pnlInputBuku.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 850, 225));

        javax.swing.GroupLayout pnlTblBukuLayout = new javax.swing.GroupLayout(pnlTblBuku);
        pnlTblBuku.setLayout(pnlTblBukuLayout);
        pnlTblBukuLayout.setHorizontalGroup(
            pnlTblBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 667, Short.MAX_VALUE)
        );
        pnlTblBukuLayout.setVerticalGroup(
            pnlTblBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlPasienLayout = new javax.swing.GroupLayout(pnlPasien);
        pnlPasien.setLayout(pnlPasienLayout);
        pnlPasienLayout.setHorizontalGroup(
            pnlPasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPasienLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlInputBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 853, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlTblBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlPasienLayout.setVerticalGroup(
            pnlPasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPasienLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPasienLayout.createSequentialGroup()
                        .addComponent(pnlTblBuku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(8, 8, 8))
                    .addGroup(pnlPasienLayout.createSequentialGroup()
                        .addComponent(pnlInputBuku, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
                        .addGap(237, 237, 237))))
        );

        pnlUtama.add(pnlPasien, "cardPasien");

        pnlInputBuku1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setText("Daftar Obat");
        pnlInputBuku1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel8.setText("Id Obat");
        pnlInputBuku1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel9.setText("Jenis Obat");
        pnlInputBuku1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel10.setText("Harga");
        pnlInputBuku1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, -1, -1));

        txtIdobat.setEnabled(false);
        pnlInputBuku1.add(txtIdobat, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 180, -1));
        pnlInputBuku1.add(txtNamaobat, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 180, -1));

        cbbobat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kapsul", "Sirup" }));
        pnlInputBuku1.add(cbbobat, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 180, -1));

        txtHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHargaActionPerformed(evt);
            }
        });
        pnlInputBuku1.add(txtHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, 180, -1));

        btnSimpanObat.setText("Simpan");
        btnSimpanObat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanObatActionPerformed(evt);
            }
        });
        pnlInputBuku1.add(btnSimpanObat, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 50, -1, -1));

        btnHapus1.setText("Hapus");
        btnHapus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapus1ActionPerformed(evt);
            }
        });
        pnlInputBuku1.add(btnHapus1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 130, 70, -1));

        btnUpdate1.setText("Ubah");
        btnUpdate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdate1ActionPerformed(evt);
            }
        });
        pnlInputBuku1.add(btnUpdate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 90, 70, -1));

        jLabel19.setText("Nama Obat");
        pnlInputBuku1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        tblObat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblObat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblObatMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblObat);

        pnlInputBuku1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 847, 225));

        javax.swing.GroupLayout pnlObatLayout = new javax.swing.GroupLayout(pnlObat);
        pnlObat.setLayout(pnlObatLayout);
        pnlObatLayout.setHorizontalGroup(
            pnlObatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlObatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlInputBuku1, javax.swing.GroupLayout.DEFAULT_SIZE, 853, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlObatLayout.setVerticalGroup(
            pnlObatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlObatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlInputBuku1, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
                .addGap(237, 237, 237))
        );

        pnlUtama.add(pnlObat, "cardObat");

        pnlInputBuku2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnHapusjdw.setText("Hapus");
        btnHapusjdw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusjdwActionPerformed(evt);
            }
        });
        pnlInputBuku2.add(btnHapusjdw, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 150, 70, -1));

        btnUpdatejdw.setText("Ubah");
        btnUpdatejdw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdatejdwActionPerformed(evt);
            }
        });
        pnlInputBuku2.add(btnUpdatejdw, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, 70, -1));

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel15.setText("Daftar Jadwal Dokter");
        pnlInputBuku2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 210, 30));

        btnSimpanjdw.setText("Simpan");
        btnSimpanjdw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanjdwActionPerformed(evt);
            }
        });
        pnlInputBuku2.add(btnSimpanjdw, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, -1, -1));

        jLabel14.setText("Tanggal Praktek");
        pnlInputBuku2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 100, -1));

        jLabel16.setText("Spesialis");
        pnlInputBuku2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, -1, -1));

        jLabel20.setText("ID Dokter");
        pnlInputBuku2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, 20));

        jLabel21.setText("ID Jadwal");
        pnlInputBuku2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel22.setText("Nama Dokter");
        pnlInputBuku2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, -1, -1));

        txtIdjadwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdjadwalActionPerformed(evt);
            }
        });
        pnlInputBuku2.add(txtIdjadwal, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 130, -1));

        txtIddokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIddokterActionPerformed(evt);
            }
        });
        pnlInputBuku2.add(txtIddokter, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 130, -1));
        pnlInputBuku2.add(txtNamadokter, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, 130, -1));
        pnlInputBuku2.add(txtSpesialis, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, 130, -1));
        pnlInputBuku2.add(DateChoose1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 150, -1));

        tblJadwal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblJadwal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblJadwalMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblJadwal);

        pnlInputBuku2.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 847, 234));

        javax.swing.GroupLayout pnlJadwalLayout = new javax.swing.GroupLayout(pnlJadwal);
        pnlJadwal.setLayout(pnlJadwalLayout);
        pnlJadwalLayout.setHorizontalGroup(
            pnlJadwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlJadwalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlInputBuku2, javax.swing.GroupLayout.DEFAULT_SIZE, 853, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlJadwalLayout.setVerticalGroup(
            pnlJadwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlJadwalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlInputBuku2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(246, 246, 246))
        );

        pnlUtama.add(pnlJadwal, "cardJadwal");

        pnlPembelian.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel23.setText("Data Pembelian");
        pnlPembelian.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 170, -1));

        jLabel27.setText("ID Dokter");
        pnlPembelian.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, -1));

        jLabel30.setText("ID Pasien");
        pnlPembelian.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 90, -1));

        jLabel25.setText("ID Obat");
        pnlPembelian.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 80, -1));

        jLabel31.setText("Harga CheckUp :");
        pnlPembelian.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, 100, -1));

        jLabel32.setText("Harga Obat");
        pnlPembelian.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 360, 100, -1));

        jLabel33.setText("Total Harga ");
        pnlPembelian.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 440, 80, 20));

        jLabel34.setText("Nama Pasien");
        pnlPembelian.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 100, -1));

        tblPembelianpsn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPembelianpsn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPembelianpsnMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(tblPembelianpsn);

        pnlPembelian.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 853, 140));

        tblPembelianobat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPembelianobat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPembelianobatMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(tblPembelianobat);

        pnlPembelian.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 5, 853, 130));

        jId_dokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jId_dokterActionPerformed(evt);
            }
        });
        pnlPembelian.add(jId_dokter, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, 150, -1));
        pnlPembelian.add(jId_pasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, 150, -1));
        pnlPembelian.add(jNama_pasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 440, 150, -1));
        pnlPembelian.add(jId_obat, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 480, 150, -1));

        jHarga_obat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jHarga_obatActionPerformed(evt);
            }
        });
        pnlPembelian.add(jHarga_obat, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 360, 150, -1));

        jTotalharga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTotalhargaActionPerformed(evt);
            }
        });
        pnlPembelian.add(jTotalharga, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 440, 150, -1));

        lblHarga.setText("Rp.50000");
        pnlPembelian.add(lblHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 520, 150, 20));

        jQty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jQtyActionPerformed(evt);
            }
        });
        pnlPembelian.add(jQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 400, 150, -1));

        jLabel35.setText("Qty");
        pnlPembelian.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 400, 100, -1));

        btnpesan.setText("Pesan");
        btnpesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpesanActionPerformed(evt);
            }
        });
        pnlPembelian.add(btnpesan, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 480, 90, -1));

        jLabel1.setText("Rp.");
        pnlPembelian.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 440, -1, 20));

        pnlUtama.add(pnlPembelian, "cardPembelian");

        pnlTransaksi.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel24.setText("Data Transaksi");
        pnlTransaksi.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 170, -1));

        jLabel29.setText("Total Harga");
        pnlTransaksi.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, -1, -1));

        tblTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTransaksiMouseClicked(evt);
            }
        });
        jScrollPane9.setViewportView(tblTransaksi);

        pnlTransaksi.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 5, 853, 130));

        txtcetaktotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtcetaktotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcetaktotalActionPerformed(evt);
            }
        });
        pnlTransaksi.add(txtcetaktotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, 150, -1));

        jButton1.setText("Hapus");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        pnlTransaksi.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 100, -1));

        jLabel36.setText("ID Transaksi");
        pnlTransaksi.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        jLabel37.setText("ID Pasien");
        pnlTransaksi.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        jLabel38.setText("Nama Pasien");
        pnlTransaksi.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        jLabel39.setText("Qty");
        pnlTransaksi.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        jLabel40.setText("Harga");
        pnlTransaksi.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, -1));

        txtcetakidtrans.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtcetakidtrans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcetakidtransActionPerformed(evt);
            }
        });
        pnlTransaksi.add(txtcetakidtrans, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 150, -1));

        txtcetakidpasien.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtcetakidpasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcetakidpasienActionPerformed(evt);
            }
        });
        pnlTransaksi.add(txtcetakidpasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 150, -1));

        txtcetaknamapasien.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtcetaknamapasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcetaknamapasienActionPerformed(evt);
            }
        });
        pnlTransaksi.add(txtcetaknamapasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 150, -1));

        txtcetakqty.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtcetakqty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcetakqtyActionPerformed(evt);
            }
        });
        pnlTransaksi.add(txtcetakqty, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 150, -1));

        txtcetakharga.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtcetakharga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcetakhargaActionPerformed(evt);
            }
        });
        pnlTransaksi.add(txtcetakharga, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 150, -1));

        btnCetak.setText("Tampilkan Struk");
        btnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakActionPerformed(evt);
            }
        });
        pnlTransaksi.add(btnCetak, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 150, -1));

        area.setColumns(20);
        area.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        area.setRows(5);
        jScrollPane1.setViewportView(area);

        pnlTransaksi.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 460, 400));

        btnCetakstruk.setText("Cetak");
        btnCetakstruk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakstrukActionPerformed(evt);
            }
        });
        pnlTransaksi.add(btnCetakstruk, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 460, 70, 40));

        jButton2.setText("Segarkan");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        pnlTransaksi.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 100, -1));

        pnlUtama.add(pnlTransaksi, "cardTransaksi");

        jMenu1.setText("Account");

        jMenuItem1.setText("Sign Out");
        jMenuItem1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem1MouseClicked(evt);
            }
        });
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlUtama, javax.swing.GroupLayout.PREFERRED_SIZE, 865, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 851, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlUtama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPasienActionPerformed
        // TODO add your handling code here:
        cl = (CardLayout) pnlUtama.getLayout();
        cl.show(pnlUtama, "cardPasien");
    }//GEN-LAST:event_btnPasienActionPerformed

    private void btnJadwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJadwalActionPerformed
        // TODO add your handling code here:
        cl = (CardLayout) pnlUtama.getLayout();
        cl.show(pnlUtama, "cardJadwal");
    }//GEN-LAST:event_btnJadwalActionPerformed

    private void btnObatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObatActionPerformed
        // TODO add your handling code here:
        cl = (CardLayout) pnlUtama.getLayout();
        cl.show(pnlUtama, "cardObat");
    }//GEN-LAST:event_btnObatActionPerformed

    private void btnSimpanPSNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanPSNActionPerformed
        // TODO add your handling code here:
        String nama = txtNama.getText();
        String alamat = txtAlam.getText();
        Object genderobj = cbbGender.getSelectedItem();
        String gender = genderobj.toString();
        String nohp =txtNotelp.getText();
        String pekerjaan=txtPekerjaan.getText();   
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String date = sdf.format(DateChoose.getDate());
        pasien ps = new pasien(nama,alamat, gender, nohp,pekerjaan,date);
        klinik.exec.ExecutePsn epsn = new klinik.exec.ExecutePsn();
        int hasil = epsn.insertpsn(ps);
        if(hasil >0){
            JOptionPane.showMessageDialog(null, "Data berhasil di simpan");
            setDataPasien();
        }
        else{
            JOptionPane.showMessageDialog(null, "Data gagal di simpan");
        }
    }//GEN-LAST:event_btnSimpanPSNActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        String kode = txtIdpasien.getText();
         klinik.exec.ExecutePsn epsn = new  klinik.exec.ExecutePsn();
        int hasil = epsn.deletepsn(kode);
        if(hasil >0){
            JOptionPane.showMessageDialog(null, "Data berhasil di hapus");
            setDataPasien();
        }
        else{
            JOptionPane.showMessageDialog(null, "Data gagal di hapus");
        }

    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        String strkode = txtIdpasien.getText();
        int kode = Integer.parseInt(strkode);
        String nama = txtNama.getText();
        String alamat = txtAlam.getText();
        Object genderobj = cbbGender.getSelectedItem();
        String gender = genderobj.toString();
        String nohp =txtNotelp.getText();
        String pekerjaan=txtPekerjaan.getText(); 
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String date = sdf.format(DateChoose.getDate());
        pasien ps = new pasien(kode, nama,alamat, gender, nohp,pekerjaan,date);
        klinik.exec.ExecutePsn epsn = new klinik.exec.ExecutePsn();
        int hasil = epsn.updatepsn(ps);
        if(hasil >0){
            JOptionPane.showMessageDialog(null, "Data berhasil diubah");
            setDataPasien();
        }
        else{
            JOptionPane.showMessageDialog(null, "Data gagal diubah");
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void tblPasienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPasienMouseClicked
        // TODO add your handling code here:
        int row = tblPasien.getSelectedRow();
        String kode = tblPasien.getValueAt(row, 0).toString();
        String nama = tblPasien.getValueAt(row, 1).toString();        
        String alamat = tblPasien.getValueAt(row, 2).toString();
        String gender = tblPasien.getValueAt(row, 3).toString();
        String nohp = tblPasien.getValueAt(row, 4).toString();
        String pekerjaan = tblPasien.getValueAt(row, 5).toString();
        String date = tblPasien.getValueAt(row, 6).toString();
        txtIdpasien.setText(kode);
        txtNama.setText(nama);
        txtNotelp.setText(nohp);
        txtAlam.setText(alamat);
        cbbGender.getSelectedItem();
        txtPekerjaan.setText(pekerjaan);
        DateChoose.getDate();
    }//GEN-LAST:event_tblPasienMouseClicked

    private void txtNotelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNotelpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNotelpActionPerformed

    private void txtHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHargaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtHargaActionPerformed

    private void btnSimpanObatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanObatActionPerformed
        // TODO add your handling code here:
        String nama = txtNamaobat.getText();
        Object obatobj = cbbobat.getSelectedItem();
        String jobat = obatobj.toString();
        String harga = txtHarga.getText();
        int hargaa = Integer.parseInt(harga);  
        obat obt = new obat(nama,jobat,hargaa);
        klinik.exec.ExecuteObat epsn = new klinik.exec.ExecuteObat();
        int hasil = epsn.insertobt(obt);
        if(hasil >0){
            JOptionPane.showMessageDialog(null, "Data berhasil di simpan");
            setDataObat();
        }
        else{
            JOptionPane.showMessageDialog(null, "Data gagal di simpan");
        }
    }//GEN-LAST:event_btnSimpanObatActionPerformed

    private void btnHapus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapus1ActionPerformed
        String kode = txtIdobat.getText();
         klinik.exec.ExecuteObat epsn = new klinik.exec.ExecuteObat();
        int hasil = epsn.deleteobt(kode);
        if(hasil >0){
            JOptionPane.showMessageDialog(null, "Data berhasil di hapus");
            setDataObat();
        }
        else{
            JOptionPane.showMessageDialog(null, "Data gagal di hapus");
        }
    }//GEN-LAST:event_btnHapus1ActionPerformed

    private void btnUpdate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdate1ActionPerformed
        String strkode = txtIdobat.getText();
        int kode = Integer.parseInt(strkode);
        String nama = txtNamaobat.getText();
        Object obatobj = cbbobat.getSelectedItem();
        String obatt = obatobj.toString();
        String harga = txtHarga.getText();
        int hargaa = Integer.parseInt(harga);
        obat obt = new obat(kode, nama, obatt, hargaa);
        klinik.exec.ExecuteObat eobt = new klinik.exec.ExecuteObat();
        int hasil = eobt.updateobat(obt);
        if(hasil >0){
            JOptionPane.showMessageDialog(null, "Data berhasil diubah");
            setDataObat();
        }
        else{
            JOptionPane.showMessageDialog(null, "Data gagal diubah");
        }
    }//GEN-LAST:event_btnUpdate1ActionPerformed

    private void tblObatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblObatMouseClicked
        // TODO add your handling code here:
        int row = tblObat.getSelectedRow();
        String id_obat = tblObat.getValueAt(row, 0).toString();
        String nama_obat = tblObat.getValueAt(row, 1).toString();
        String jenis_obat = tblObat.getValueAt(row, 2).toString();
        String harga = tblObat.getValueAt(row, 3).toString();
        txtIdobat.setText(id_obat);
        txtNamaobat.setText(nama_obat);
        cbbobat.getSelectedItem();
        txtHarga.setText(harga);
    }//GEN-LAST:event_tblObatMouseClicked

    private void btnHapusjdwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusjdwActionPerformed
        // TODO add your handling code here:
         String id_jadwal = txtIdjadwal.getText();
         klinik.exec.ExecuteJadwal epsn = new  klinik.exec.ExecuteJadwal();
        int hasil = epsn.deletejdw(id_jadwal);
        if(hasil >0){
            JOptionPane.showMessageDialog(null, "Data berhasil di hapus");
            setDataJadwal();
        }
        else{
            JOptionPane.showMessageDialog(null, "Data gagal di hapus");
        }
    }//GEN-LAST:event_btnHapusjdwActionPerformed

    private void btnUpdatejdwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdatejdwActionPerformed
        String kodejadwal = txtIdjadwal.getText();
        String kode = txtIddokter.getText();
        int kodedokter = Integer.parseInt(kode);
        String namadokter = txtNamadokter.getText();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String date = sdf.format(DateChoose1.getDate());
        String spesialis = txtSpesialis.getText();
        jadwal jdl = new jadwal(namadokter, kodejadwal, kodedokter, date, spesialis);
        klinik.exec.ExecuteJadwal eobt = new klinik.exec.ExecuteJadwal();
        int hasil = eobt.updatejdw(jdl);
        if(hasil >0){
            JOptionPane.showMessageDialog(null, "Data berhasil diubah");
            setDataJadwal();
        }
        else{
            JOptionPane.showMessageDialog(null, "Data gagal diubah");
        }
        
    }//GEN-LAST:event_btnUpdatejdwActionPerformed

    private void tblJadwalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblJadwalMouseClicked
        // TODO add your handling code here:
        int row = tblJadwal.getSelectedRow();
        String id_jadwal = tblJadwal.getValueAt(row, 0).toString();
        String id_dokter = tblJadwal.getValueAt(row, 1).toString();        
        String nama_dokter = tblJadwal.getValueAt(row, 2).toString();
        String tglprak = tblJadwal.getValueAt(row, 3).toString();
        String spesialis = tblJadwal.getValueAt(row, 4).toString();
        txtIdjadwal.setText(id_jadwal);
        txtIddokter.setText(id_dokter);
        txtNamadokter.setText(nama_dokter);
        txtSpesialis.setText(spesialis);
        DateChoose1.getDate();
    }//GEN-LAST:event_tblJadwalMouseClicked

    private void btnSimpanjdwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanjdwActionPerformed
        // TODO add your handling code here:
        String kode = txtIdjadwal.getText();
        String nama = txtNamadokter.getText();
        String spesialis = txtSpesialis.getText(); 
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String date = sdf.format(DateChoose1.getDate());
        jadwal jd = new jadwal(nama,kode,date,spesialis);
        klinik.exec.ExecuteJadwal ejdw = new klinik.exec.ExecuteJadwal();
        int hasil = ejdw.insertjdw(jd);
        if(hasil >0){
            JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
            setDataJadwal();
        }
        else{
            JOptionPane.showMessageDialog(null, "Data gagal disimpan");
        }
        
    }//GEN-LAST:event_btnSimpanjdwActionPerformed

    private void txtIdjadwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdjadwalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdjadwalActionPerformed

    private void txtIddokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIddokterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIddokterActionPerformed

    private void btnPembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPembelianActionPerformed
        cl = (CardLayout) pnlUtama.getLayout();
        cl.show(pnlUtama, "cardPembelian");
    }//GEN-LAST:event_btnPembelianActionPerformed

    private void tblPembelianobatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPembelianobatMouseClicked
        int row = tblPembelianobat.getSelectedRow();
        String id_obat = tblPembelianobat.getValueAt(row, 0).toString();
        String nama_obat = tblPembelianobat.getValueAt(row, 1).toString();
        String jenis_obat = tblPembelianobat.getValueAt(row, 2).toString();
        String harga = tblPembelianobat.getValueAt(row, 3).toString();
        jId_obat.setText(id_obat);
        jHarga_obat.setText(harga);
    }//GEN-LAST:event_tblPembelianobatMouseClicked

    private void tblPembelianpsnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPembelianpsnMouseClicked
        int row = tblPembelianpsn.getSelectedRow();
        String kode = tblPembelianpsn.getValueAt(row, 0).toString();
        String nama = tblPembelianpsn.getValueAt(row, 1).toString();        
        String alamat = tblPembelianpsn.getValueAt(row, 2).toString();
        String gender = tblPembelianpsn.getValueAt(row, 3).toString();
        String nohp = tblPembelianpsn.getValueAt(row, 4).toString();
        String pekerjaan = tblPembelianpsn.getValueAt(row, 5).toString();
        String date = tblPembelianpsn.getValueAt(row, 6).toString();
        jId_pasien.setText(kode);
        jNama_pasien.setText(nama);
    }//GEN-LAST:event_tblPembelianpsnMouseClicked

    private void jId_dokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jId_dokterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jId_dokterActionPerformed

    private void jTotalhargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTotalhargaActionPerformed

    }//GEN-LAST:event_jTotalhargaActionPerformed

    private void jHarga_obatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jHarga_obatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jHarga_obatActionPerformed

    private void tblTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTransaksiMouseClicked
        // TODO add your handling code here:
        int row = tblTransaksi.getSelectedRow();
        String id_transaksi= tblTransaksi.getValueAt(row, 0).toString();
        String id_dokter = tblTransaksi.getValueAt(row, 1).toString();        
        String id_pasien = tblTransaksi.getValueAt(row, 2).toString();
        String nama_pasien= tblTransaksi.getValueAt(row, 3).toString();
        String id_obat = tblTransaksi.getValueAt(row, 4).toString();
        String Quantity = tblTransaksi.getValueAt(row, 5).toString();
        String harga_obat = tblTransaksi.getValueAt(row, 6).toString();
        String total_harga = tblTransaksi.getValueAt(row, 7).toString();
        txtcetakidtrans.setText(id_transaksi);
        txtcetakidpasien.setText(id_pasien);
        txtcetaknamapasien.setText(nama_pasien);
        txtcetakharga.setText(harga_obat);
        txtcetakqty.setText(Quantity);
        txtcetaktotal.setText(total_harga);
        
    }//GEN-LAST:event_tblTransaksiMouseClicked

    private void txtcetaktotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcetaktotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcetaktotalActionPerformed

    private void btnTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransaksiActionPerformed
        cl = (CardLayout) pnlUtama.getLayout();
        cl.show(pnlUtama, "cardTransaksi");
    }//GEN-LAST:event_btnTransaksiActionPerformed

    private void jQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jQtyActionPerformed
        int harga,jumlah,qty,total;
        
        harga = Integer.valueOf(jHarga_obat.getText());
        qty = Integer.valueOf(jQty.getText());
        total = (harga * qty)+ 50000 ;
        jTotalharga.setText(String.valueOf(total));        // TODO add your handling code here:
    }//GEN-LAST:event_jQtyActionPerformed

    private void btnpesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpesanActionPerformed
        String id_dokter = jId_obat.getText();
        int iddokter = Integer.parseInt(id_dokter);
        String id_pasien = jId_pasien.getText();
        int idpasien = Integer.parseInt(id_pasien);
        String nama_pasien = jNama_pasien.getText();
        String id_obat = jId_obat.getText();
        int idobat = Integer.parseInt(id_obat);
        String hargaobat = jHarga_obat.getText();
        int hargaobatt = Integer.parseInt(hargaobat);
        String qty = jQty.getText();
        int qtyy = Integer.parseInt(qty);
        String totalharga = jTotalharga.getText(); 
        int totalhargaa = Integer.parseInt(totalharga);
        transaksi tf = new transaksi(iddokter, idpasien, idobat, hargaobatt, totalhargaa, nama_pasien, qtyy);
        klinik.exec.ExecuteTransaksi etf = new klinik.exec.ExecuteTransaksi();
        int hasil = etf.inserttf(tf);
        if(hasil >0){
            JOptionPane.showMessageDialog(null, "Data berhasil di simpan");
            setDataTransaksi();
        }
        else{
            JOptionPane.showMessageDialog(null, "Data gagal di simpan");
        }
    }//GEN-LAST:event_btnpesanActionPerformed

    private void txtcetakidtransActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcetakidtransActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcetakidtransActionPerformed

    private void txtcetakidpasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcetakidpasienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcetakidpasienActionPerformed

    private void txtcetaknamapasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcetaknamapasienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcetaknamapasienActionPerformed

    private void txtcetakqtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcetakqtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcetakqtyActionPerformed

    private void txtcetakhargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcetakhargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcetakhargaActionPerformed

    private void btnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakActionPerformed
        // TODO add your handling code here:
        area.setText(area.getText()+"***********************************\n");
        area.setText(area.getText()+"*                     Struk Transaksi                   *\n");
        area.setText(area.getText()+"***********************************\n");
        
        area.setText(area.getText()+"Id Transaksi     : "+txtcetakidtrans.getText()+"\n");
        area.setText(area.getText()+"Id pasien         : "+txtcetakidpasien.getText()+"\n");
        area.setText(area.getText()+"Nama pasien    : "+txtcetaknamapasien.getText()+"\n");
        area.setText(area.getText()+"Qty                  : "+txtcetakqty.getText()+"\n");
        area.setText(area.getText()+"Harga Obat      : "+txtcetakharga.getText()+"\n");
        area.setText(area.getText()+"Total Harga      : "+txtcetaktotal.getText()+"\n");
        
        
    }//GEN-LAST:event_btnCetakActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        area.setText("");
         String id_jadwal = txtcetakidtrans.getText();
         klinik.exec.ExecuteTransaksi epsn = new  klinik.exec.ExecuteTransaksi();
        int hasil = epsn.deletetf(id_jadwal);
        if(hasil >0){
            JOptionPane.showMessageDialog(null, "Data berhasil di hapus");
            setDataTransaksi();
        }
        else{
            JOptionPane.showMessageDialog(null, "Data gagal di hapus");
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem1MouseClicked

    }//GEN-LAST:event_jMenuItem1MouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.dispose();
            new MainLogin().setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btnCetakstrukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakstrukActionPerformed
        // TODO add your handling code here:
        try
        {
          area.print();  
        }
        catch(Exception e)
        {   
        } 
    }//GEN-LAST:event_btnCetakstrukActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     area.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFormStore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFormStore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFormStore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFormStore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFormStore().setVisible(true);
            }
        });
    }
    private CardLayout cl;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser DateChoose;
    private com.toedter.calendar.JDateChooser DateChoose1;
    private javax.swing.JTextArea area;
    private javax.swing.JButton btnCetak;
    private javax.swing.JButton btnCetakstruk;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnHapus1;
    private javax.swing.JButton btnHapusjdw;
    private javax.swing.JButton btnJadwal;
    private javax.swing.JButton btnObat;
    private javax.swing.JButton btnPasien;
    private javax.swing.JButton btnPembelian;
    private javax.swing.JButton btnSimpanObat;
    private javax.swing.JButton btnSimpanPSN;
    private javax.swing.JButton btnSimpanjdw;
    private javax.swing.JButton btnTransaksi;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnUpdate1;
    private javax.swing.JButton btnUpdatejdw;
    private javax.swing.JButton btnpesan;
    private javax.swing.JComboBox<String> cbbGender;
    private javax.swing.JComboBox<String> cbbobat;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JTextField jHarga_obat;
    private javax.swing.JTextField jId_dokter;
    private javax.swing.JTextField jId_obat;
    private javax.swing.JTextField jId_pasien;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JTextField jNama_pasien;
    private javax.swing.JTextField jQty;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTextField jTotalharga;
    private javax.swing.JLabel lblHarga;
    private javax.swing.JPanel pnlInputBuku;
    private javax.swing.JPanel pnlInputBuku1;
    private javax.swing.JPanel pnlInputBuku2;
    private javax.swing.JPanel pnlJadwal;
    private javax.swing.JPanel pnlObat;
    private javax.swing.JPanel pnlPasien;
    private javax.swing.JPanel pnlPembelian;
    private javax.swing.JPanel pnlTblBuku;
    private javax.swing.JPanel pnlTransaksi;
    private javax.swing.JPanel pnlUtama;
    private javax.swing.JTable tblJadwal;
    private javax.swing.JTable tblObat;
    private javax.swing.JTable tblPasien;
    private javax.swing.JTable tblPembelianobat;
    private javax.swing.JTable tblPembelianpsn;
    private javax.swing.JTable tblTransaksi;
    private javax.swing.JTextField txtAlam;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtIddokter;
    private javax.swing.JTextField txtIdjadwal;
    private javax.swing.JTextField txtIdobat;
    private javax.swing.JTextField txtIdpasien;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNamadokter;
    private javax.swing.JTextField txtNamaobat;
    private javax.swing.JTextField txtNotelp;
    private javax.swing.JTextField txtPekerjaan;
    private javax.swing.JTextField txtSpesialis;
    private javax.swing.JTextField txtcetakharga;
    private javax.swing.JTextField txtcetakidpasien;
    private javax.swing.JTextField txtcetakidtrans;
    private javax.swing.JTextField txtcetaknamapasien;
    private javax.swing.JTextField txtcetakqty;
    private javax.swing.JTextField txtcetaktotal;
    // End of variables declaration//GEN-END:variables
}
